package com.adapt.androidbluetoothserial.deambulateurApp.enums;

public enum MessageEnum {

    MOTOR_FRAGMENT_SUCCESS("MOTORS FRAGMENT"),
    MOTOR_FRAGMENT_ERROR("MOTORS FRAGMENT FAILED"),
    MOTOR_FRAGMENT_WARNING("MOTORS FRAGMENT WARNING"),
    MOTOR_FRAGMENT_DEBUG("MOTORS FRAGMENT DEBUG"),

    SENSORS_FRAGMENT_SUCCESS("SENSORS FRAGMENT"),
    SENSORS_FRAGMENT_ERROR("SENSORS FRAGMENT FAILED"),
    SENSORS_FRAGMENT_WARNING("SENSORS FRAGMENT WARNING"),
    SENSORS_FRAGMENT_DEBUG("SENSORS FRAGMENT DEBUG"),

    PROFILE_FRAGMENT_SUCCESS("PROFILE FRAGMENT"),
    PROFILE_FRAGMENT_ERROR("PROFILE FRAGMENT FAILED"),
    PROFILE_FRAGMENT_WARNING("PROFILE FRAGMENT WARNING"),
    PROFILE_FRAGMENT_DEBUG("PROFILE FRAGMENT DEBUG"),

    // Pager view model messages
    PAGER_ACT_MESSAGE_SUCCESS ("PAGER ACTIVITY"),
    PAGER_ACT_MESSAGE_ERROR ("PAGER ACTIVITY FAILED"),
    PAGER_ACT_MESSAGE_WARNING ("PAGER ACTIVITY WARNING"),
    PAGER_ACT_MESSAGE_DEBUG ("PAGER ACTIVITY DEBUG"),

    // Pager view model messages
    MAIN_ACT_MESSAGE_SUCCESS ("MAIN ACTIVITY"),
    MAIN_ACT_MESSAGE_ERROR ("MAIN ACTIVITY FAILED"),
    MAIN_ACT_MESSAGE_WARNING ("MAIN ACTIVITY WARNING"),
    MAIN_ACT_MESSAGE_DEBUG ("MAIN ACTIVITY DEBUG"),

    // Pager view model messages
    PAGER_VM_LOG_MESSAGE_SUCCESS ("PAGER VIEW MODEL"),
    PAGER_VM_LOG_MESSAGE_ERROR ("PAGER VIEW MODEL FAILED"),
    PAGER_VM_LOG_MESSAGE_WARNING ("PAGER VIEW MODEL WARNING"),
    PAGER_VM_LOG_MESSAGE_DEBUG ("PAGER VIEW MODEL DEBUG"),

    // JSON Parser
    JSON_PARSER_EXCEPTION ("Json parsing error: ");
    private final String message;

    MessageEnum(String message) {
        this.message = message;
    }

    public String getMessage() {return message; }

}
